# Generated by Django 6.0.5 on 2026-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('naissance', 'Acte de naissance'), ('mariage', 'Acte de mariage'), ('deces', 'Acte de décès')], max_length=20, verbose_name="Type d'acte")),
                ('fichier', models.FileField(upload_to='actes/', verbose_name='Fichier PDF')),
                ('nom_complet', models.CharField(blank=True, max_length=200, verbose_name='Nom complet concerné')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acte',
                'verbose_name_plural': 'Actes',
                'db_table': 'etat_civil_acte',
                'ordering': ['-date_upload'],
            },
        ),
    ]
