# Generated by Django 6.0.5 on 2026-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_civil', '0002_actenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='declarant_contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contact du déclarant'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='declarant_noms',
            field=models.CharField(blank=True, max_length=200, verbose_name='Noms et prénoms du déclarant'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='declarant_qualite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qualité / Statut du déclarant'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_assistant_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Personne ayant assisté la mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_rang_naissance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang de naissance'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='enfant_type_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de naissance'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='mere_date_dernier_vivant',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier né vivant'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='mere_nb_deces_foetal',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de décès fœtaux'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier_centre',
            field=models.CharField(blank=True, max_length=200, verbose_name="Centre d'état civil"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier_noms',
            field=models.CharField(blank=True, max_length=200, verbose_name="Noms et prénoms de l'officier"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier_qualite',
            field=models.CharField(blank=True, max_length=200, verbose_name="Qualité / Statut de l'officier"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier_signature',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signature (référence)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='pere_date_dernier_vivant',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier né vivant'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='pere_nb_deces_foetal',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de décès fœtaux'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='pere_nb_enfants_vivants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants vivants"),
        ),
    ]
