# Generated by Django 6.0.5 on 2026-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('naissance', 'Acte de naissance'), ('mariage', 'Acte de mariage'), ('deces', 'Acte de décès')], max_length=20)),
                ('fichier', models.FileField(upload_to='actes/')),
                ('nom_complet', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'requette_acte_upload',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.CharField(editable=False, max_length=20, unique=True)),
                ('numero_acte', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_etablissement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('enfant_noms', models.CharField(max_length=200)),
                ('enfant_prenoms', models.CharField(max_length=200)),
                ('enfant_date_naissance', models.DateField()),
                ('enfant_lieu_naissance', models.CharField(max_length=200)),
                ('mere_noms', models.CharField(max_length=200)),
                ('mere_date_naissance', models.DateField()),
                ('mere_lieu_residence', models.CharField(max_length=200)),
                ('mere_duree_residence', models.CharField(blank=True, max_length=100)),
                ('mere_profession', models.CharField(blank=True, max_length=200)),
                ('mere_contact', models.CharField(blank=True, max_length=30)),
                ('mere_situation_matrimoniale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('mariee', 'Mariée'), ('divorcee', 'Divorcée'), ('veuve', 'Veuve')], max_length=20)),
                ('mere_niveau_scolaire', models.CharField(blank=True, choices=[('non_scolarise', 'Non scolarisé(e)'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur')], max_length=20)),
                ('mere_nationalite', models.CharField(blank=True, max_length=100)),
                ('mere_cni', models.CharField(blank=True, max_length=50)),
                ('mere_nb_enfants', models.PositiveIntegerField(default=0)),
                ('pere_noms', models.CharField(max_length=200)),
                ('pere_date_lieu_naissance', models.CharField(max_length=200)),
                ('pere_domicile', models.CharField(blank=True, max_length=200)),
                ('pere_profession', models.CharField(blank=True, max_length=200)),
                ('pere_contact', models.CharField(blank=True, max_length=30)),
                ('pere_niveau_scolaire', models.CharField(blank=True, choices=[('non_scolarise', 'Non scolarisé(e)'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur')], max_length=20)),
                ('pere_nationalite', models.CharField(blank=True, max_length=100)),
                ('pere_cni', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acte de naissance',
                'verbose_name_plural': 'Actes de naissance',
                'db_table': 'requette_acte',
                'ordering': ['-created_at'],
            },
        ),
    ]
